### ISSUE TITLE
After upgrade from vscode-java v0.77.0 to v0.78.0 can't debug tests

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-java-pack#614]
After upgrade [vscode-java](https://github.com/redhat-developer/vscode-java) from v0.77.0 to v0.78.0 can't debug tests, only execute them

##### Environment
- Operating System: Linux
- JDK version: 11
- Visual Studio Code version: 1.55.2
- Java extension version: 0.78.0

##### Steps To Reproduce
1. Open a maven project with JUnit tests
2. Try run the test in debug mode

##### Current Result
An error message appears and the test can't be run

##### Expected Result
Test is run stopping at any break point

##### Additional Informations
I I downgrade to version 0.77.0 everything works as expected.

The error message in the log is: 
`java.lang.NoSuchMethodError: 'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'`

see: https://github.com/redhat-developer/vscode-java/issues/1915

**Comment by smngong** [comment]
I got same error.
Had to back to v0.77.0 to make debug work.

**Comment by rubensa** [comment]
@testforstephen [just released a hotfix release 0.33.1 for debugger](https://github.com/microsoft/vscode-java-debug/issues/995#issuecomment-829922505). It will work with both vscode-java@0.77.0 and 0.78.0.
