### PR TITLE
fix uri of scripts to pass CORS policy

### LINKED ISSUE #1102: All webviews fail to show correctly on VS Code 1.73.0
It works well on 1.72.2.

#### logs
Access to script at 'vscode-resource:/Users/username/.vscode/extensions/vscjava.vscode-java-pack-0.25.5/out/assets/overview/index.js' from origin 'vscode-webview://0dmmqnvj174oplb46sd9ejs1ekit868llogvsvrtqb2p5orhqf2e' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, https, vscode-webview, chrome-untrusted, data, vscode-file, chrome, chrome-extension.

### PR DESCRIPTION
**Pull request by Eskibear**
fix #1102 
- Now use `webview.asWebviewUri` to generate correct Uri for scripts, instead of constructing Uri on our own... Root cause is, in vscode1.73, corresponding URI changes from `vscode-resource:/path-to-script` to something like `https://file+.vscode-resource.vscode-cdn.net/path-to-script`

### CODE REVIEW

**Comment by Eskibear** [comment]
Now after fixing script Uri, scripts are successfully loaded, but below webview still get new errors. 

```
Uncaught TypeError: __webpack_modules__[moduleId].call is not a function
    at __webpack_require__ (index.js:57713:42)
    at Module.<anonymous> (index.js:53228:63)
    at __webpack_require__ (index.js:57713:42)
    at module.exports (index.js:57339:19)
    at __webpack_require__ (index.js:57713:42)
    at Object.<anonymous> (index.js:56599:31)
    at __webpack_require__ (index.js:57713:42)
    at Object.<anonymous> (index.js:56481:44)
    at __webpack_require__ (index.js:57713:42)
    at Object.<anonymous> (index.js:56434:42)
```

Possibly related to redux i guess.
- formatting @cscherryy
- classpath @jdneo 
- install-jdk @Eskibear 

All the other webviews seem to work well.

**Comment by Eskibear** [comment]
above errors are due to webpack packing dirty `immer` package. PR bits works well.
